language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: e4EF04uSWE+8Vu09UH9RvjRolgbMjm5nXhdPLFbQqA9AL+4tt22b+swRQg8RVOqvh7EbkxDN3rae6QUY6DYVbcrOPL83b6cdiPzIPMpD04SlWED+bq6FxkRLzxmxnSAAuNKFStuZhX4yfzSdsmcRgoPWURQS3YRZSNjuNmAf04UUs9mVrOsnC7MA8ng6pkVPSlsjPj/wJB96/bsdVhF095P/X3mhzenYaEBKxWblqEcp/bFfF3lBADkrx6+VH4o9ZZ9ozkQ7fJ9It1WIbEnvMfuwZKXC2sScL/NgRUDpWIB7xe6Adw3ggptwiIDFHBq6zpHQwRZ4mIoacD30Kxh1y4ZM3SvkxnK6KoXIluFFT2r69otq6gfOfFlngyxNEQ/PmUxo+59Dk3Z2SJVf9HlXd99fQXWGxDakGLBHKW2L8qtEx/rHBoTnGDRk4b8am+ZXOKVPOdqNtjcy+WayOIjsqrD8M43ne4pYZZuTPH8HJb2rqFMufHhoXachvwXdLSqGn6eIq7ERq2IcuuBg0ejDxXKy5Ekv39H3rdcnyz4Sg/6xgFNZR7yS8B6C4NF9mBPAZLgJk4JatAZTjMAFzIYuASbPURd4Wx5EyTGhTGYZgsE30iWeI7QzJ6XocXWb/tmqYmlAflK7ZgAwg5Rz61CuAMe36Meh2GftexR8RUK0s6s=
  app: tranquil-plateau-10397
  on:
    repo: mscottcam/dash_capstone
