language: node_js
node_js: node
services:
- mongodb
deploy: tranquil-plateau-10397
  provider: heroku
  api_key:
    secure: HKMrAPXR2iUnqq2Cxc/uP4B3Y1lYFQTvmN55EwJdRX0Ut8n6CdgPm1t89My4JuLbIogWdpba+9k14A9ElG0gOmSsjCiSVu0aBVmA6bofDisamoZZvphwIynNIC+2d+OazUZnjTU95wafwo99NBrVtLMXDk0PzJ6fBKYi742J1d0POcNvKP9iSp83h+mcNWxMnbGz22LS9E8rfaDqPkYO4PkJTnAHOx44vctBlXlm/0MnmX5Zd6mBdZ2QPUmPJsGcoYwQrf9+X01hGdySmiLz3sfwiDbXpDZV1QhIwrFOm+Jzd+MKn872PEhCzLjaTsmamf6nhLpWg+vAAKLqjsKkF1F0SfEPwPhg6cpC/Ebu2xTsdfPeCJljQICbYGPWpj0HOtrFY2TMsCuAhR8pi3phB0YQytMAqaF4KvsCJtkzGFfCLnnEe+IT2tW2dWhkZk8Ias541sc1Ui8cR7vVyXA6xrbfjvUtXh/6GLeSMby8eMGIiGLyKS0fEpLdlkz4k0Yoro3mJjmreiTnrUCfsAs1yJ96W2UD541YDVJ9PvT2SJJIxcPb9wjrlNnRw0vO8q3GsQmC+D4A4UhUC5+/bQJFOfLH7e4olteMaPVh/BcaFgBeq7eUEDip1ky6Ar2iYtKFrOuWAS43N0mP3hHc8wGHSrdCDT7hF7SjxftugkHWbAI=
  app: dash_capstone
  on:
    repo: dash_capstone
